import logging
import time

import numpy as np
from gym import spaces

from gym_diplomacy.envs import diplomacy_env
from gym_diplomacy.envs import proto_message_pb2

FORMAT = "%(levelname)s -- [%(filename)s:%(lineno)s - %(funcName)s()] %(message)s"
logging.basicConfig(format=FORMAT)

logging_level = 'DEBUG'
level = getattr(logging, logging_level)
logger = logging.getLogger(__name__)
logger.setLevel(level)
logger.disabled = False

### LEVELS OF LOGGING (in increasing order of severity)
# DEBUG	    Detailed information, typically of interest only when diagnosing problems.
# INFO	    Confirmation that things are working as expected.
# WARNING	An indication that something unexpected happened, or indicative of some problem in the near future
# (e.g. 'disk space low'). The software is still working as expected.
# ERROR	    Due to a more serious problem, the software has not been able to perform some function.
# CRITICAL	A serious error, indicating that the program itself may be unable to continue running.

### CONSTANTS
NUMBER_OF_PLAYERS = 7
NUMBER_OF_OPPONENTS = NUMBER_OF_PLAYERS - 1
NUMBER_OF_PROVINCES = 75
NUMBER_OF_PHASES_AHEAD = 20


def observation_data_to_observation(observation_data: proto_message_pb2.ObservationData) -> np.array:
    """
    This function takes a Protobuf ObservationData and generates the necessary information for the agent to act.

    :param observation_data: A Protobuf ObservationData object.
    :return: A list with the structure [observation, reward, done, info]. Observation is an np array, reward is a float,
    done is a boolean and info is a dictionary.
    """
    number_of_provinces = len(observation_data.provinces)

    if number_of_provinces != NUMBER_OF_PROVINCES:
        raise ValueError("Number of provinces is not consistent. Constant variable is '{}' while received number of "
                         "provinces is '{}'.".format(NUMBER_OF_PROVINCES, number_of_provinces))

    observation = np.zeros(number_of_provinces * 2)

    for province in observation_data.provinces:
        # simply for type hint and auto-completion
        province: proto_message_pb2.ProvinceData = province

        # id - 1 because the ids begin at 1
        observation[(province.id - 1) * 2] = province.owner
        observation[(province.id - 1) * 2 + 1] = province.sc

    reward = observation_data.previousActionReward
    done = observation_data.done
    info = {"info_string": observation_data.info}

    return observation, reward, done, info


def action_to_deal_data(action: np.ndarray) -> proto_message_pb2.DealData:
    """
    This function takes a NumPy array generated by the DRL model and turns it into a DealData object that can be sent to Bandana.
    :param action: The NumPy array corresponding to the agent's action.
    :return: A DealData object with the translation of the NumPy array to a deal.
    """
    deal_data: proto_message_pb2.DealData = proto_message_pb2.DealData()

    if action.size != 6:
        raise ValueError("The array given does not have the correct number of elements. Expected {}, got {} from {}"
                         .format(6, action.size, action))

    our_move: proto_message_pb2.DealData.MTOOrderData = proto_message_pb2.DealData.MTOOrderData()
    their_move: proto_message_pb2.DealData.MTOOrderData = proto_message_pb2.DealData.MTOOrderData()

    our_move.startProvince = action[0]
    our_move.destinationProvince = action[1]

    their_move.startProvince = action[3]
    their_move.destinationProvince = action[4]

    deal_data.powerToPropose = action[2]
    deal_data.ourMove.CopyFrom(our_move)
    deal_data.theirMove.CopyFrom(their_move)
    deal_data.phasesFromNow = action[5]

    return deal_data


class DiplomacyNegotiationEnv(diplomacy_env.DiplomacyEnv):
    """
    The main OpenAI Gym class. It encapsulates an environment with
    arbitrary behind-the-scenes dynamics. An environment can be
    partially or fully observed.
    The main API methods that users of this class need to know are:
        step
        reset
        render
        close
        seed
    And set the following attributes:
        action_space: The Space object corresponding to valid actions
        observation_space: The Space object corresponding to valid observations
        reward_range: A tuple corresponding to the min and max possible rewards
    Note: a default reward range set to [-inf,+inf] already exists. Set it if you want a narrower range.
    The methods are accessed publicly as "step", "reset", etc.. The
    non-underscored versions are wrapper methods to which we may add
    functionality over time.
    """

    def render(self, mode='human'):
        raise NotImplementedError

    def _init_observation_space(self):
        # Observation space: [[province owner, province has supply center] * number of provinces]
        # Eg: If observation_space[2] is [5, 0], then the second province belongs to player 5 and does NOT have a SC

        observation_space_description = []

        for i in range(NUMBER_OF_PROVINCES):
            observation_space_description.extend([NUMBER_OF_PLAYERS, 2])

        self.observation_space = spaces.MultiDiscrete(observation_space_description)

    def _init_action_space(self):
        # Action space:
        # [
        # province to move OUR from,
        # province to move OUR to,
        # opponent to propose OC to,
        # province for THEIR unit to move,
        # destination province of THEIR unit,
        # how many phases from now should it be done (0 means the current one)
        # ]
        #
        # Eg: Action [1, 2, 2, 5, 6, 2] proposes an order
        # commitment for us to move from province 1 to 2 and an order commitment to player 2 for moving a unit from
        # province 5 to 6, 2 phases from now

        self.action_space = spaces.MultiDiscrete([NUMBER_OF_PROVINCES, NUMBER_OF_PROVINCES,
                                                  NUMBER_OF_OPPONENTS, NUMBER_OF_PROVINCES, NUMBER_OF_PROVINCES,
                                                  NUMBER_OF_PHASES_AHEAD])

    def handle_request(self, request: bytearray) -> bytes:
        request_data: proto_message_pb2.BandanaRequest = proto_message_pb2.BandanaRequest()
        request_data.ParseFromString(request)

        logger.info("Executing _handle of request...")

        if request_data.type is proto_message_pb2.BandanaRequest.INVALID:
            raise ValueError("Type of BandanaRequest is 'INVALID'. Something bad happened on BANDANA side.",
                             request_data)

        elif request_data.type is proto_message_pb2.BandanaRequest.GET_DEAL_REQUEST:
            response_data = self._handle_get_deal_request(request_data)

        elif request_data.type is proto_message_pb2.BandanaRequest.SEND_GAME_END:
            response_data = self._handle_send_game_end_request(request_data)

        else:
            raise NotImplementedError("There is no handle for request of type '{}'.".format(request_data.type))

        logger.info("Returning handler response.")

        # Using this just for IDE autocompletion
        response_data: proto_message_pb2.DiplomacyGymResponse = response_data

        return response_data.SerializeToString()

    def _handle_get_deal_request(self,
                                 request_data: proto_message_pb2.BandanaRequest) -> proto_message_pb2.DiplomacyGymResponse:
        observation_data: proto_message_pb2.ObservationData = request_data.observation
        self.observation, self.reward, self.done, self.info = observation_data_to_observation(observation_data)

        response_data: proto_message_pb2.DiplomacyGymResponse = proto_message_pb2.DiplomacyGymResponse()
        response_data.type = proto_message_pb2.DiplomacyGymResponse.CONFIRM

        # No longer waiting for request from BANDANA to be processed
        self.waiting_for_observation_to_be_processed = False

        # Waiting for action from the agent
        self.waiting_for_action = True

        # This timeout is used when env.close() is not called.
        # For example, in the baselines agents, close() is not called.
        # Therefore, there must be a way for telling the cycle to stop.
        # This may disappear once we refactor.
        time_to_timeout = 10
        timeout = time.time() + time_to_timeout  # timeout after ten seconds

        # Wait for action to be taken. If env should terminate, then stop waiting.
        while self.waiting_for_action:
            if self.done:
                # Return empty deal because game is over and BANDANA needs a response
                logger.debug("Sending empty deal to finalize program.")
                return response_data

            if time.time() > timeout:
                logger.info("Timed out waiting for step function. Either step is taking too long or it hasn't been "
                            "called in '{}' seconds.".format(time_to_timeout))

                # Bandana needs to be killed, otherwise it'll ask for one more action when it shouldn't
                self._kill_bandana()

                return response_data

        # Once we have the action, send it as a deal
        deal_data: proto_message_pb2.DealData = action_to_deal_data(self.action)
        response_data.deal.CopyFrom(deal_data)

        return response_data

    def _handle_send_game_end_request(self,
                                      request_data: proto_message_pb2.BandanaRequest) -> proto_message_pb2.DiplomacyGymResponse:
        logger.debug("Handling 'SEND_GAME_END'.")

        observation_data: proto_message_pb2.ObservationData = request_data.observation
        self.observation, self.reward, self.done, self.info = observation_data_to_observation(observation_data)

        if not self.done:
            raise ValueError("Received game end notification, but value of 'done' is not 'True'.")

        response_data: proto_message_pb2.DiplomacyGymResponse = proto_message_pb2.DiplomacyGymResponse()
        response_data.type = proto_message_pb2.DiplomacyGymResponse.CONFIRM

        self.waiting_for_action = False
        logger.debug("'waiting_for_action': {}".format(self.waiting_for_action))

        self.waiting_for_observation_to_be_processed = False

        return response_data


if __name__ == "__main__":
    gym = DiplomacyNegotiationEnv()
