# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto_message_pb2 as proto__message__pb2


class DiplomacyGymServiceStub(object):
  """*
  It's important that the communication between modules remains as simple as possible.

  In this particular case, all logic regarding converting observation and action into
  arrays is done on the side of BANDANA. Therefore most messages have fields which correspond to numbers.

  The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAction = channel.unary_unary(
        '/dip_q.DiplomacyGymService/GetAction',
        request_serializer=proto__message__pb2.BandanaRequest.SerializeToString,
        response_deserializer=proto__message__pb2.DiplomacyGymResponse.FromString,
        )


class DiplomacyGymServiceServicer(object):
  """*
  It's important that the communication between modules remains as simple as possible.

  In this particular case, all logic regarding converting observation and action into
  arrays is done on the side of BANDANA. Therefore most messages have fields which correspond to numbers.

  The greeting service definition.
  """

  def GetAction(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiplomacyGymServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAction': grpc.unary_unary_rpc_method_handler(
          servicer.GetAction,
          request_deserializer=proto__message__pb2.BandanaRequest.FromString,
          response_serializer=proto__message__pb2.DiplomacyGymResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dip_q.DiplomacyGymService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
