# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Command(google___protobuf___message___Message):
    class CommandType(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> Command.CommandType: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[Command.CommandType]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, Command.CommandType]]: ...
    START_TEST = typing___cast(CommandType, 0)
    RESULTS = typing___cast(CommandType, 1)
    SHUTDOWN = typing___cast(CommandType, 3)

    type = ... # type: Command.CommandType
    name = ... # type: typing___Text

    @property
    def data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[GameData]: ...

    def __init__(self,
        type : typing___Optional[Command.CommandType] = None,
        name : typing___Optional[typing___Text] = None,
        data : typing___Optional[typing___Iterable[GameData]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Command: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"data",u"name",u"type"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"data",b"name",b"type"]) -> None: ...

class PowerData(google___protobuf___message___Message):
    class PowerName(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> PowerData.PowerName: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[PowerData.PowerName]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, PowerData.PowerName]]: ...
    None = typing___cast(PowerName, 0)
    AUS = typing___cast(PowerName, 1)
    ENG = typing___cast(PowerName, 2)
    FRA = typing___cast(PowerName, 3)
    GER = typing___cast(PowerName, 4)
    ITA = typing___cast(PowerName, 5)
    RUS = typing___cast(PowerName, 6)
    TUR = typing___cast(PowerName, 7)

    name = ... # type: PowerData.PowerName

    def __init__(self,
        name : typing___Optional[PowerData.PowerName] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PowerData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"name"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"name"]) -> None: ...

class ProvinceData(google___protobuf___message___Message):
    sc = ... # type: bool

    @property
    def owner(self) -> PowerData: ...

    def __init__(self,
        owner : typing___Optional[PowerData] = None,
        sc : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ProvinceData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"owner"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"owner",u"sc"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"owner",b"owner"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[b"owner",b"sc"]) -> None: ...

class GameData(google___protobuf___message___Message):

    @property
    def provinces(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ProvinceData]: ...

    def __init__(self,
        provinces : typing___Optional[typing___Iterable[ProvinceData]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GameData: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"provinces"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"provinces"]) -> None: ...
